name: ems_rwanda
description: Unit Converter App that takes in a value and unit and outputs a conversion in another unit.

dependencies:
  flutter:
    sdk: flutter
  flutter_sparkline: "^0.0.4"
  flutter_staggered_grid_view: "^0.1.4"
  intl: "^0.15.0"
  tuple: "^1.0.1"
  date_utils: "^0.0.1"
  flutter_calendar: "^0.0.1"
  font_awesome_flutter: "^6.0.0"
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
      sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/data/regular_units.json
   - assets/icons/area.png
   - assets/icons/currency.png
   - assets/icons/digital_storage.png
   - assets/icons/length.png
   - assets/icons/mass.png
   - assets/icons/power.png
   - assets/icons/time.png
   - assets/icons/volume.png
   - assets/images/emma-watson.jpg
   - assets/images/microphone.png
   - assets/images/wallet.png
   - assets/images/joystick.png
   - assets/diamond.png
   - assets/ipad.jpg
   - assets/icons/availability.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
   - family: Raleway
     fonts:
      - asset: third_party/Raleway-Regular.ttf
   - family: LineAwesome
     fonts:
      - asset: assets/fonts/line-awesome.ttf
   - family: Timeburner
     fonts:
      - asset: assets/fonts/timeburnernormal.ttf
      - asset: assets/fonts/timeburnerbold.ttf
        weight: 700

  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
